### ISSUE TITLE
OrmExtensionModelTrait is missing

### ISSUE THREAD

**Issue by sergor5** [4spacesdk/CI4RESTExtension#1]
Hi, I was trying your extensions (rest and orm). In docs you(@Martin-4Spaces or @Kevin-4Spaces ) said 

> If you use OrmExtension add this trait to your base model: **use OrmExtensionModelTrait;**. This will allow RestExtension to filter your resources based on your models and their relations.

But I downloaded the repo and searched the "OrmExtensionModelTrait" in software called FileSeek and it didn't find anything about it. Can you update docs or help me from here? I just want to try QueryParser class

**Comment by Martin-4Spaces** [comment]
@sergor5 
You are correct. The docs need an update.
```
If you use OrmExtension add this trait to your base model: use RestExtension\ResourceModelTrait; or extend RestExtension\Core\Model. This will allow RestExtension to filter your resources based on your models and their relations.
```

**Comment by sergor5** [comment]
And also in Commands>ControllerGenerator.php
```php
<?php namespace App\Controllers;

use App\Core\ResourceController;

class {$name} extends ResourceController {

}
```
you used 

> App\Core\ResourceController

But there is no reference or an example for that

**Comment by Martin-4Spaces** [comment]
Sure. This generator should not belong in this repository. 
Hereby removed from master.
Thank you.

**Comment by sergor5** [comment]
Added **`Events::on('pre_system', [\RestExtension\Hooks::class, 'preSystem']);`**
![image](https://user-images.githubusercontent.com/29211821/114367098-c3ecda80-9b84-11eb-96e1-8e7a10e20be3.png)

Then added the QueryParser to the BaseController
![image](https://user-images.githubusercontent.com/29211821/114366968-a3248500-9b84-11eb-8ce4-f6b745be2234.png)

Then created the ProductModel model and the Product entity
![image](https://user-images.githubusercontent.com/29211821/114367002-addf1a00-9b84-11eb-910f-1bbd07f8e987.png)
![image](https://user-images.githubusercontent.com/29211821/114367835-850b5480-9b85-11eb-919d-4cec073fdcde.png)

And finaly used the model in Products controller
![image](https://user-images.githubusercontent.com/29211821/114367056-b899af00-9b84-11eb-8bc0-a034d54bae5f.png)

But when I make this request with postman `GET http://localhost:8080/test/api/v1/products?filter=firmaid:33555&limit=10`
it returns all results.
If add `var_dump($this->queryParser); die;` to the Products.php controller I can see the seperated array of filter as 
![image](https://user-images.githubusercontent.com/29211821/114368744-6063ac80-9b86-11eb-9425-33a2be83c147.png)
So the QueryParser work but it seems like it doesn't apply to the model. 
Is there anything I've done wrong?

**Comment by Martin-4Spaces** [comment]
There is a missing link between the controller and RestExtension.
We need to call `restGet` on the model to get advantage of RestExtension.
Try this
```
$products = (new ProductModel())->restGet($id, $this->queryParser);
return $this->response->setJSON($products);
```

If this works, you could take a look at ResourceControllerTrait. You can use it on BaseController to add generic CRUD functions for all controllers. Or create a new ResourceController with ResourceControllerTrait and extend ResourceController from desired controllers.

**Comment by sergor5** [comment]
Added recommenden code
![image](https://user-images.githubusercontent.com/29211821/114371829-8fc7e880-9b89-11eb-8e37-b45a5e506173.png)

Made request but still it returns first row in the table
![image](https://user-images.githubusercontent.com/29211821/114371928-abcb8a00-9b89-11eb-8a0d-137daf349093.png)

And by the way thanks for quick responses and for helping out

**Comment by sergor5** [comment]
Also these are the versions
![image](https://user-images.githubusercontent.com/29211821/114372421-314f3a00-9b8a-11eb-9ea7-8b9bc711e42a.png)

**Comment by Martin-4Spaces** [comment]
Ahh, you need to do a `return $this->response->setJSON($products->allToArray());`.
Np. Happy to help.
I'm also to find on CodeIgniter Slack under the name Martin(4Spaces).

**Comment by sergor5** [comment]
Did it but this time fetches all table which has 401 rows of data
![image](https://user-images.githubusercontent.com/29211821/114375473-57c2a480-9b8d-11eb-90d4-a162e4ab7bf3.png)
I mean it doesnt apply the filtering and the limit

**Comment by sergor5** [comment]
Can you make a little example for a single simple table (simple as having id, title, price columns)

**Comment by Martin-4Spaces** [comment]
@sergor5 
Here you go https://github.com/4spacesdk/CI4-RestOrmExtensionSample
I think I know what you are missing. You need to implement `ResourceModelInterface` for `ProductModel`.

**Comment by sergor5** [comment]
> @sergor5
> Here you go https://github.com/4spacesdk/CI4-RestOrmExtensionSample
> I think I know what you are missing. You need to implement `ResourceModelInterface` for `ProductModel`.

Worked, thanks! And I will examine the code you provided.
Also a recommendation: Add a query **fields** to be able to return fields only needed
