### ISSUE TITLE
Not included fields return null

### ISSUE THREAD

**Issue by sergor5** [4spacesdk/CI4RESTExtension#2]
I'm trying to add fields query to this extension. Like this:

Create folder Fields in /vendor/4spacesdk/ci4restextension/Fields.
Create file called QueryField.php in Fields folder.
```php
<?php

namespace RestExtension\Fields;

/**
 *
 * @property string $property
 * @property string $direction
 */
class QueryField
{
    public $ignoreAuto = false;

    public static function parse($field)
    {
        $item = new QueryField();
        if ($field == "")
            $item->fieldName = null;
        else
            $item->fieldName = $field;
        return $item;
    }

    public function isRelationField(): bool
    {
        return strpos($this->fieldName, '.') !== false;
    }
}

```

In QueryParser.php add:
```php
use RestExtension\Fields\QueryField;
```
![image](https://user-images.githubusercontent.com/29211821/114569745-e7e01700-9c7d-11eb-8a87-422d977531c8.png)
![image](https://user-images.githubusercontent.com/29211821/114569798-f3cbd900-9c7d-11eb-8ff1-d8e5ab66ef5c.png)
![image](https://user-images.githubusercontent.com/29211821/114569845-00e8c800-9c7e-11eb-90f8-b73b551faadf.png)
![image](https://user-images.githubusercontent.com/29211821/114569888-0c3bf380-9c7e-11eb-8620-77c545606fb5.png)
![image](https://user-images.githubusercontent.com/29211821/114569955-1827b580-9c7e-11eb-8832-2acf70078bed.png)

In ResourceModelTrait.php add:
```php
use RestExtension\Fields\QueryField;
```
![image](https://user-images.githubusercontent.com/29211821/114570112-3beafb80-9c7e-11eb-8633-727b412f2b34.png)
![image](https://user-images.githubusercontent.com/29211821/114570469-853b4b00-9c7e-11eb-9391-43ead519f775.png)

The issue is when I add fields query to url like `http://localhost:8780/products?limit=10&fields=title` it returns other fields as null:
![image](https://user-images.githubusercontent.com/29211821/114570861-da775c80-9c7e-11eb-9cea-07174e192a6a.png)

on my table:
![image](https://user-images.githubusercontent.com/29211821/114571019-fc70df00-9c7e-11eb-84a1-bcdbee656fff.png)

Do you know what can cause it to return all fields?

**Comment by Martin-4Spaces** [comment]
I like the idea. I’ll take a look a it tomorrow.

**Comment by Martin-4Spaces** [comment]
It seems like your solution works for selecting a subset of fields from the database. This part is okay.
We also need to define a subset of fields to return from `toArray()`. 
Here is the toArray method in OrmExtension.
![CI4-RestOrmExtensionSample_–___PhpstormProjects_CI4-RestOrmExtensionSample_ci4_vendor_4spacesdk_ci4ormextension_DataMapper_EntityTrait_php](https://user-images.githubusercontent.com/9819124/114832968-626c7c00-9dcf-11eb-920c-a8e52901098a.png)
It iterates over database columns and creates an array with keys corresponding to the database columns. Except if the column is part if `hiddenFields`. Even if the field is empty or null it will still be added to the array. Ensuring a complete entity. 
What you want is to define the fields. 
I suggest adding a fourth argument to the method called `fields`. If this argument is set we could do a `array_filter` on `$fields` between line 20 and 21. Ensuring that we only iterate the given fields.
Do you get the idea?

Then we should add the same four arguments to `allToArray`. Like this.
![CI4-RestOrmExtensionSample_–___PhpstormProjects_CI4-RestOrmExtensionSample_ci4_vendor_4spacesdk_ci4ormextension_DataMapper_EntityTrait_php](https://user-images.githubusercontent.com/9819124/114834167-96946c80-9dd0-11eb-83c3-d1bc0d00e999.png)

**Comment by sergor5** [comment]
Ok, I'll try the idea.

**Comment by sergor5** [comment]
Ok did it. 
Added allToArrayWithFields and toArrayWithFields functions to switch places of $fields_filter variable in order to pass only one variable to the function.
![image](https://user-images.githubusercontent.com/29211821/114883533-af6f4300-9e0d-11eb-8bd5-5d343fb580f3.png)
![image](https://user-images.githubusercontent.com/29211821/114883357-864eb280-9e0d-11eb-837d-9d83f26a24bf.png)


Checking array of column names against filter array
![image](https://user-images.githubusercontent.com/29211821/114883187-58696e00-9e0d-11eb-95b8-3979ee5065cf.png)

Then used new functions:
![image](https://user-images.githubusercontent.com/29211821/114883668-cf066b80-9e0d-11eb-8208-b1369e6efd93.png)

And the result:
![image](https://user-images.githubusercontent.com/29211821/114883722-d9c10080-9e0d-11eb-89df-005dbf1e5bc6.png)

**Comment by sergor5** [comment]
Forgot to tell about the ProducModel's implementation: 
![image](https://user-images.githubusercontent.com/29211821/114899883-05e37e00-9e1c-11eb-97e3-67bb49201091.png)

Added to QueryParser.php:
![image](https://user-images.githubusercontent.com/29211821/114899998-1f84c580-9e1c-11eb-8f21-a0d49f4346ca.png)

And finaly modified the toArray if statement 
from:
![image](https://user-images.githubusercontent.com/29211821/114883187-58696e00-9e0d-11eb-95b8-3979ee5065cf.png)
to:
![image](https://user-images.githubusercontent.com/29211821/114900329-712d5000-9e1c-11eb-84f6-ab320c795fa4.png)
Before modifying it hwen you didnt add fields query to url you would get errors.

**Comment by Martin-4Spaces** [comment]
Good work!
Would u like to create a PR?

Martin Hansen
Backend

Telefon 23 72 02 89 | Website www.4spaces.dk <http://www.4spaces.dk/> | Email ***@***.*** ***@***.***>

**Comment by sergor5** [comment]
Sorry but what does it mean?

**Comment by Martin-4Spaces** [comment]
If you want your improvements to be part of this repository you can create Pull Requests for both repositories. https://github.com/4spacesdk/CI4RESTExtension/pulls

**Comment by sergor5** [comment]
Ok, but I need first update some places

**Comment by sergor5** [comment]
If you want I can send all files that changed because I don't have time for it. And also I used 1.0.0-beta.32 version because I didn't update Codeigniter 4 for my project

**Comment by Martin-4Spaces** [comment]
Yes please do that.

**Comment by sergor5** [comment]
https://gist.github.com/sergor5/adc6cfd6770393e6f59a12f8b505f7f1

**Comment by sergor5** [comment]
Test it in the same version I used so if anything is missing for the gist link I will add or update the gist.
versions:
- CodeIgniter 4.0.4
- ci4ormextension 1.0.0-beta.32
- ci4restextension 1.0.0-beta.32

**Comment by Martin-4Spaces** [comment]
@sergor5 
Sorry for the late response. I finally got the time to implement this feature. It is now part of ci4ormextension 1.0.0 and ci4restextension 1.0.0.
Thank you for your help!
